# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSuplier', models.CharField(max_length=255, null=True)),
                ('alamat', models.CharField(max_length=255, null=True)),
                ('CP', models.CharField(max_length=255, null=True)),
                ('notelp1', models.CharField(max_length=25, null=True)),
                ('notelp2', models.CharField(max_length=25, null=True)),
                ('notelp3', models.CharField(max_length=25, null=True)),
                ('notelp4', models.CharField(max_length=25, null=True)),
                ('norekening', models.CharField(max_length=25, null=True)),
                ('bank', models.CharField(max_length=255, null=True)),
                ('atasnama', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Suplier',
            },
        ),
    ]
