# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaBarang', models.CharField(max_length=255, null=True)),
                ('Harga', models.IntegerField()),
                ('Diskon', models.IntegerField()),
                ('DiskonRp', models.IntegerField()),
                ('HargaDiskon', models.IntegerField()),
                ('Ongkir', models.IntegerField()),
                ('Modal', models.IntegerField()),
                ('HargaJual', models.IntegerField()),
                ('TglVerify', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IDBarang',
            },
        ),
        migrations.RenameField(
            model_name='suplier',
            old_name='nameSuplier',
            new_name='namaSuplier',
        ),
        migrations.AlterField(
            model_name='suplier',
            name='notelp1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='notelp2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='notelp3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='notelp4',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='idbarang',
            name='Suplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembukuan.Suplier'),
        ),
    ]
