# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0002_auto_20160304_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoRekening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank', models.CharField(max_length=255, null=True)),
                ('NoRekBank', models.CharField(max_length=25, null=True)),
                ('AtasNama', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'NoRekening',
            },
        ),
        migrations.CreateModel(
            name='NoTelepon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telp', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'NoTelepon',
            },
        ),
        migrations.RenameField(
            model_name='idbarang',
            old_name='namaBarang',
            new_name='NamaBarang',
        ),
        migrations.RemoveField(
            model_name='idbarang',
            name='TglVerify',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='atasnama',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='norekening',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='notelp1',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='notelp2',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='notelp3',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='notelp4',
        ),
        migrations.AddField(
            model_name='notelepon',
            name='Suplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NoTelpSuplier', to='pembukuan.Suplier'),
        ),
        migrations.AddField(
            model_name='norekening',
            name='Suplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NoRekSuplier', to='pembukuan.Suplier'),
        ),
    ]
