# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan', '0003_auto_20160311_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idbarang',
            name='DiskonRp',
        ),
        migrations.RemoveField(
            model_name='idbarang',
            name='Modal',
        ),
    ]
